---
title: "Assesmentreport"
author: "A.Maklennan"
format: html 
embed-resources: true
editor: visual
---

## Introduction

## Material and Methodes 



```{r}
library(readr)
library(here)
library("tidyverse")

data <-read.csv(here("data","raw", "insurance_with_date.csv"))

library(unibeCols)
library("ggplot2")
library(dplyr)
library(lubridate)
library(readr)

ebola <- read_csv(here("data/raw/ebola.csv"))
library("ggplot2")

ebola2 <- ebola %>% filter(Date<as.Date("2015-03-31"))

library(ggplot2)

ebola2<-ebola%>%
filter(Country %in% c("Senegal", "Sierra Leone", "Nigeria"))

ggplot(ebola2, aes(x = Date, y = Cum_conf_cases, color = Country)) +
  geom_point(size = 3, alpha = 0.7) +
  labs(title = "Cumulative Confirmed Cases by Country",
       x = "Date",
       y = "Cumulative Confirmed Cases") +
  theme_minimal()

ebola2<-ebola%>%
  filter(Country %in% c("Senegal", "Sierra Leone", "Nigeria"))
plot_ebola2_col_v0<-ggplot(data=ebola2, 
                           mapping = aes(x = Date, y = Cum_conf_cases, fill=Country)) +
geom_col(position = "stack")

plot_ebola2_col_v0

# Save the plot as a PNG using ggsave




```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
